[package]
name = "chippy"
version = "0.1.0"
authors = ["Sahan Fernando <sahan.h.fernando@gmail.com>"]

[dependencies]
byteorder="1.0.0"
rand="0.3.0"
argparse="*"

[dependencies.sdl2]
version="0.31.0"
default-features = false
features = ["ttf"]
